# For the full spec setting and usage, see ./pkg/apis/frameworkcontroller/v1/types.go
apiVersion: frameworkcontroller.microsoft.com/v1
kind: Framework
metadata:
  name: batchjob
  namespace: ns01
spec:
  executionType: Start
  minMember: 3
  priorityClassName: master-pri
  queue: q1
  retryPolicy:
    fancyRetryPolicy: true
    maxRetryCount: 1
  taskRoles:
    - name: ps
      taskNumber: 1
      frameworkAttemptCompletionPolicy:
        minFailedTaskCount: 1
        minSucceededTaskCount: -1
      task:
        retryPolicy:
          fancyRetryPolicy: true
          maxRetryCount: 1
        pod:
          spec:
            restartPolicy: Never
            priorityClassName: master-pri
            containers:
              - name: ps
                image: busybox
                schedulerName: kube-batch
                command: ["sh", "-c","sleep 10"]
                resources:
                  requests:
                    cpu: "1"
    - name: worker
      taskNumber: 2
      frameworkAttemptCompletionPolicy:
        minFailedTaskCount: 1
        minSucceededTaskCount: -1
      task:
        retryPolicy:
          fancyRetryPolicy: true
          maxRetryCount: 1
        pod:
          spec:
            restartPolicy: Never
            priorityClassName: worker-pri
            containers:
              - name: worker
                image: busybox
                schedulerName: kube-batch
                command: ["sh", "-c","sleep 10"]
                resources:
                  requests:
                    cpu: "2"
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns01
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: master-pri
value: 100
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: worker-pri
value: 10
---
apiVersion: scheduling.incubator.k8s.io/v1alpha1
kind: Queue
metadata:
  name: q1
spec:
  weight: 2