# For the full spec setting and usage, see ./pkg/apis/frameworkcontroller/v1/types.go
apiVersion: frameworkcontroller.microsoft.com/v1
kind: Framework
metadata:
  name: job03
  namespace: ns01
spec:
  executionType: Start
  priorityClassName: master-pri
  retryPolicy:
    fancyRetryPolicy: true
    maxRetryCount: 1
  taskRoles:
    - name: worker
      taskNumber: 1
      frameworkAttemptCompletionPolicy:
        minFailedTaskCount: 1
        minSucceededTaskCount: -1
      task:
        retryPolicy:
          fancyRetryPolicy: true
          maxRetryCount: 1
        pod:
          spec:
            restartPolicy: Never
            containers:
              - name: ubuntu
                image: busybox
                schedulerName: kube-batch
                command: ["sh", "-c","sleep 10"]
                resources:
                  requests:
                    cpu: "1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns01
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: master-pri
value: 100