// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	types "k8s.io/apimachinery/pkg/types"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompletionPolicySpec) DeepCopyInto(out *CompletionPolicySpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompletionPolicySpec.
func (in *CompletionPolicySpec) DeepCopy() *CompletionPolicySpec {
	if in == nil {
		return nil
	}
	out := new(CompletionPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompletionPolicyTriggerStatus) DeepCopyInto(out *CompletionPolicyTriggerStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompletionPolicyTriggerStatus.
func (in *CompletionPolicyTriggerStatus) DeepCopy() *CompletionPolicyTriggerStatus {
	if in == nil {
		return nil
	}
	out := new(CompletionPolicyTriggerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompletionStatus) DeepCopyInto(out *CompletionStatus) {
	*out = *in
	in.Type.DeepCopyInto(&out.Type)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompletionStatus.
func (in *CompletionStatus) DeepCopy() *CompletionStatus {
	if in == nil {
		return nil
	}
	out := new(CompletionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompletionType) DeepCopyInto(out *CompletionType) {
	*out = *in
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = make([]CompletionTypeAttribute, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompletionType.
func (in *CompletionType) DeepCopy() *CompletionType {
	if in == nil {
		return nil
	}
	out := new(CompletionType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerCompletionStatus) DeepCopyInto(out *ContainerCompletionStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerCompletionStatus.
func (in *ContainerCompletionStatus) DeepCopy() *ContainerCompletionStatus {
	if in == nil {
		return nil
	}
	out := new(ContainerCompletionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Framework) DeepCopyInto(out *Framework) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(FrameworkStatus)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Framework.
func (in *Framework) DeepCopy() *Framework {
	if in == nil {
		return nil
	}
	out := new(Framework)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Framework) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FrameworkAttemptCompletionStatus) DeepCopyInto(out *FrameworkAttemptCompletionStatus) {
	*out = *in
	if in.CompletionStatus != nil {
		in, out := &in.CompletionStatus, &out.CompletionStatus
		*out = new(CompletionStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Trigger != nil {
		in, out := &in.Trigger, &out.Trigger
		*out = new(CompletionPolicyTriggerStatus)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FrameworkAttemptCompletionStatus.
func (in *FrameworkAttemptCompletionStatus) DeepCopy() *FrameworkAttemptCompletionStatus {
	if in == nil {
		return nil
	}
	out := new(FrameworkAttemptCompletionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FrameworkAttemptStatus) DeepCopyInto(out *FrameworkAttemptStatus) {
	*out = *in
	in.StartTime.DeepCopyInto(&out.StartTime)
	if in.RunTime != nil {
		in, out := &in.RunTime, &out.RunTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.InstanceUID != nil {
		in, out := &in.InstanceUID, &out.InstanceUID
		*out = new(types.UID)
		**out = **in
	}
	if in.ConfigMapUID != nil {
		in, out := &in.ConfigMapUID, &out.ConfigMapUID
		*out = new(types.UID)
		**out = **in
	}
	if in.CompletionStatus != nil {
		in, out := &in.CompletionStatus, &out.CompletionStatus
		*out = new(FrameworkAttemptCompletionStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.TaskRoleStatuses != nil {
		in, out := &in.TaskRoleStatuses, &out.TaskRoleStatuses
		*out = make([]*TaskRoleStatus, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(TaskRoleStatus)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FrameworkAttemptStatus.
func (in *FrameworkAttemptStatus) DeepCopy() *FrameworkAttemptStatus {
	if in == nil {
		return nil
	}
	out := new(FrameworkAttemptStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FrameworkList) DeepCopyInto(out *FrameworkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Framework, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FrameworkList.
func (in *FrameworkList) DeepCopy() *FrameworkList {
	if in == nil {
		return nil
	}
	out := new(FrameworkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FrameworkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FrameworkSpec) DeepCopyInto(out *FrameworkSpec) {
	*out = *in
	out.RetryPolicy = in.RetryPolicy
	if in.TaskRoles != nil {
		in, out := &in.TaskRoles, &out.TaskRoles
		*out = make([]*TaskRoleSpec, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(TaskRoleSpec)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FrameworkSpec.
func (in *FrameworkSpec) DeepCopy() *FrameworkSpec {
	if in == nil {
		return nil
	}
	out := new(FrameworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FrameworkStatus) DeepCopyInto(out *FrameworkStatus) {
	*out = *in
	in.StartTime.DeepCopyInto(&out.StartTime)
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	in.TransitionTime.DeepCopyInto(&out.TransitionTime)
	in.RetryPolicyStatus.DeepCopyInto(&out.RetryPolicyStatus)
	in.AttemptStatus.DeepCopyInto(&out.AttemptStatus)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FrameworkStatus.
func (in *FrameworkStatus) DeepCopy() *FrameworkStatus {
	if in == nil {
		return nil
	}
	out := new(FrameworkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodCompletionStatus) DeepCopyInto(out *PodCompletionStatus) {
	*out = *in
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = make([]*ContainerCompletionStatus, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ContainerCompletionStatus)
				**out = **in
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodCompletionStatus.
func (in *PodCompletionStatus) DeepCopy() *PodCompletionStatus {
	if in == nil {
		return nil
	}
	out := new(PodCompletionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetryPolicySpec) DeepCopyInto(out *RetryPolicySpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetryPolicySpec.
func (in *RetryPolicySpec) DeepCopy() *RetryPolicySpec {
	if in == nil {
		return nil
	}
	out := new(RetryPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetryPolicyStatus) DeepCopyInto(out *RetryPolicyStatus) {
	*out = *in
	if in.RetryDelaySec != nil {
		in, out := &in.RetryDelaySec, &out.RetryDelaySec
		*out = new(int64)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetryPolicyStatus.
func (in *RetryPolicyStatus) DeepCopy() *RetryPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(RetryPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskAttemptCompletionStatus) DeepCopyInto(out *TaskAttemptCompletionStatus) {
	*out = *in
	if in.CompletionStatus != nil {
		in, out := &in.CompletionStatus, &out.CompletionStatus
		*out = new(CompletionStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Pod != nil {
		in, out := &in.Pod, &out.Pod
		*out = new(PodCompletionStatus)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskAttemptCompletionStatus.
func (in *TaskAttemptCompletionStatus) DeepCopy() *TaskAttemptCompletionStatus {
	if in == nil {
		return nil
	}
	out := new(TaskAttemptCompletionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskAttemptStatus) DeepCopyInto(out *TaskAttemptStatus) {
	*out = *in
	in.StartTime.DeepCopyInto(&out.StartTime)
	if in.RunTime != nil {
		in, out := &in.RunTime, &out.RunTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.InstanceUID != nil {
		in, out := &in.InstanceUID, &out.InstanceUID
		*out = new(types.UID)
		**out = **in
	}
	if in.PodUID != nil {
		in, out := &in.PodUID, &out.PodUID
		*out = new(types.UID)
		**out = **in
	}
	if in.PodIP != nil {
		in, out := &in.PodIP, &out.PodIP
		*out = new(string)
		**out = **in
	}
	if in.PodHostIP != nil {
		in, out := &in.PodHostIP, &out.PodHostIP
		*out = new(string)
		**out = **in
	}
	if in.CompletionStatus != nil {
		in, out := &in.CompletionStatus, &out.CompletionStatus
		*out = new(TaskAttemptCompletionStatus)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskAttemptStatus.
func (in *TaskAttemptStatus) DeepCopy() *TaskAttemptStatus {
	if in == nil {
		return nil
	}
	out := new(TaskAttemptStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskRoleSpec) DeepCopyInto(out *TaskRoleSpec) {
	*out = *in
	out.FrameworkAttemptCompletionPolicy = in.FrameworkAttemptCompletionPolicy
	in.Task.DeepCopyInto(&out.Task)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskRoleSpec.
func (in *TaskRoleSpec) DeepCopy() *TaskRoleSpec {
	if in == nil {
		return nil
	}
	out := new(TaskRoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskRoleStatus) DeepCopyInto(out *TaskRoleStatus) {
	*out = *in
	if in.TaskStatuses != nil {
		in, out := &in.TaskStatuses, &out.TaskStatuses
		*out = make([]*TaskStatus, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(TaskStatus)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskRoleStatus.
func (in *TaskRoleStatus) DeepCopy() *TaskRoleStatus {
	if in == nil {
		return nil
	}
	out := new(TaskRoleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskSpec) DeepCopyInto(out *TaskSpec) {
	*out = *in
	out.RetryPolicy = in.RetryPolicy
	in.Pod.DeepCopyInto(&out.Pod)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskSpec.
func (in *TaskSpec) DeepCopy() *TaskSpec {
	if in == nil {
		return nil
	}
	out := new(TaskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskStatus) DeepCopyInto(out *TaskStatus) {
	*out = *in
	in.StartTime.DeepCopyInto(&out.StartTime)
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	in.TransitionTime.DeepCopyInto(&out.TransitionTime)
	in.RetryPolicyStatus.DeepCopyInto(&out.RetryPolicyStatus)
	in.AttemptStatus.DeepCopyInto(&out.AttemptStatus)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskStatus.
func (in *TaskStatus) DeepCopy() *TaskStatus {
	if in == nil {
		return nil
	}
	out := new(TaskStatus)
	in.DeepCopyInto(out)
	return out
}
